### ISSUE TITLE
Injected ILogger<T> not logging anything

### ISSUE THREAD

**Issue by MikePennington** [tntwist/NL.Serverless.AspNetCore#13]
I ran `dotnet new webapi` to generate a new webapi and added a log statement for testing:

```
        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            _logger.LogError("TESTING");
```

The statement will log just fine if I run the webapi using `dotnet run`, but it will not write anything to the logs if I run `func start host` and also will not log anything when I push the function app up to azure.

**Comment by tntwist** [comment]
Thanks again and its also fixed with the new version 😄 

Greetings.
