### ISSUE TITLE
Unable to resolve service for type 'System.Diagnostics.DiagnosticListener' while attempting to activate 'Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware'

### ISSUE THREAD

**Issue by baudnix** [tntwist/NL.Serverless.AspNetCore#30]
Having some trouble whenever EntityFrameworkCore is referenced to the Web App project.

After some testing it appears to throw the exception when any middleware is attempting to retrieve a service during the ApplicationBuilder.Build call.  I was able to replicate this on the sample and on a new solution.

Thought that perhaps something was getting lost amongst method invocation calls on the WebApp Startup class in the FunctionsHostStartup<>.BuildFunctionsRequestHandler handler but after stepping through the code I can't see anything.

Any help would be appreciated with this.

EntityFrameworkCore 3.1.8
NL.Serverless.AspNetCore.AzureFunctionsHost 3.0.9

**Comment by tntwist** [comment]
Hi,
I can reproduce this behavior. It seems that there is an incompatible dependencie in EF Core >= 3.1.4

As you can see the Version of "System.Diagnostics.DiagnosticSource" was increased from 4.7.0 to 4.7.1 with EF Core 3.1.4

3.1.3
![image](https://user-images.githubusercontent.com/6589385/92825399-c9582b80-f3cf-11ea-92c3-30a3bd072981.png)

3.1.4
![image](https://user-images.githubusercontent.com/6589385/92825475-dffe8280-f3cf-11ea-96ff-7f65f50a4fe9.png)

It seems that Version from EfCore > 3.1.4 are incompatible at the moment. Sorry for now the workaround will be tu use EF Core 3.1.3 😞

**Comment by stipdav** [comment]
@tntwist thanks for looking into this.  Following on from your findings I found an issue over at Azure/Azure-Functions#1613 which mentions this problem also.  Hopefully this gets picked up and sorted soon.

**Comment by tntwist** [comment]
@stipdav Nice.  I think its good to leave this issue open till it is fixed in the function runtime.

**Comment by tntwist** [comment]
Hi,
 I just released a new version with support for the new isolated function worker. You could use this version in order to fix this problem. See [here](https://github.com/tntwist/NL.Serverless.AspNetCore/issues/34#issuecomment-812208920).

**Comment by tntwist** [comment]
Just released the nuget Package. You can upgrade now and this issue should be fixed.
