### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Woland2k** [tntwist/NL.Serverless.AspNetCore#45]
Followed all the instructions with the latest 5.0 version and get a "502 - Web server received an invalid response while acting as a gateway or proxy server." after long delay when deployed in azure (works fine locally). Any suggestion?

**Comment by ChristianWeyer** [comment]
Do you have it working successfully in Azure @tntwist ?

**Comment by tntwist** [comment]
@Woland2k, @ChristianWeyer 

I could find a way to fix this. You need to create an application setting within the function app that points to the content root for the web app:

![image](https://user-images.githubusercontent.com/6589385/131023539-7bb32c8d-4f47-4998-bf40-572299fc4836.png)

The name of the setting should be ``ASPNETCORE_TEST_CONTENTROOT_NAME_OF_YOUR_WEBAPP_ASSEMBLY`` and point the value to ``C:\home\site\wwwroot\``

I leave the issue open until I updated the readme.

**Comment by tntwist** [comment]
Closed with v5.1.0
