### ISSUE TITLE
Razor Pages support

### ISSUE THREAD

**Issue by jdluzen** [tntwist/NL.Serverless.AspNetCore#7]
Hello and thanks for this great project! It's now my go-to for deploying on Functions.

I've been messing with configuration and routing relating to Razor Pages for hours now, but can't seem to get it working. It's always a 404. Any ideas?

**Comment by tntwist** [comment]
Hi there.

I´m looking into this.

**Comment by tntwist** [comment]
@jdluzen 
I figured out why the razor pages won´t be properly registered.

The problem is that the *.Views.dll File containing your compiled pages is not added to the bin directory of the function projects build output . It´s missing here: `...\YOUR.NAMESPACE\YOUR.NAMESPACE.FunctionApp\bin\Debug\netcoreapp3.1\bin`.

If you look in this folder `...\YOUR.NAMESPACE\YOUR.NAMESPACE.FunctionApp\bin\Debug\netcoreapp3.1` you will see that the assembly is actual there and has been copied. Just to the wrong place. You can copy the dll in the bin folder manually for testing and this should fix it. 

I´m looking for an way to include the *.View.dll automatically to the bin directory and give you an update.

**Comment by jdluzen** [comment]
Thanks so much, this works for running while developing.

Here's what I have for copying the file after build:
`  <Target Name="CopyCustomContent" AfterTargets="AfterBuild">
    <Copy SourceFiles="$(OutDir)/<project name>.Views.dll" DestinationFolder="$(OutDir)/bin" />
  </Target>`

Unfortunately, attempting to publish via `func azure functionapp publish <myfunc> --dotnet-cli-params -- "-c Release"` uploads successfully, but gives `Cannot bind parameter 'log' to type ILogger.` in the Azure Functions output.

I have `<RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>` set in the FunctionApp.csproj, otherwise Azure says `Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. . System.Private.CoreLib: Could not load the specified file.`

Is there a recommended way to publish/deploy one of these project to Functions?

**Comment by jdluzen** [comment]
Well, it seems that all is working now. I'm not entirely sure what was going on, but I recreated the Function and switched the runtime to `~3`. I had though that `AzureFunctionsVersion` in the csproj would have been enough to switch it on deploy and/or display an error.

**Comment by tntwist** [comment]
Thanks for the build target.
I added some additonal tasks to clean up the output of the function
```
 <Target Name="CleanUpFunctionHostTarget" AfterTargets="AfterBuild">
    <ItemGroup>
      <RazorViewDlls Include="$(OutDir)*.Views.dll"/>
      <RazorViewPdbs Include="$(OutDir)*.Views.pdb"/>
      <Executables Include="$(OutDir)*.exe" />
    </ItemGroup>
    <Move SourceFiles="@(RazorViewDlls)" DestinationFiles="@(RazorViewDlls->'$(OutDir)bin\%(Filename)%(Extension)')" />
    <Move SourceFiles="@(RazorViewPdbs)" DestinationFiles="@(RazorViewPdbs->'$(OutDir)bin\%(Filename)%(Extension)')" />
    <Delete Files="@(Executables)"></Delete>
  </Target>
```
Basicly we just move View.dll and its pdb file to the bin folder.
The generated executable of the WebApplication won´t be needed in the function, so it can be deleted. I´m going to add this to the next release.

For the `Cannot bind parameter 'log' to type ILogger``Excpetion:

Try adding logging to the service collection of the web app:
```
 // configure services for web app.
var webAppServices = new ServiceCollection();
var diagnosticSource = new DiagnosticListener(hostingEnv.ApplicationName);
webAppServices.AddSingleton<DiagnosticSource>(diagnosticSource); webAppServices.AddSingleton(diagnosticSource);
webAppServices.AddSingleton<ObjectPoolProvider>(new DefaultObjectPoolProvider());
webAppServices.AddSingleton<IHostApplicationLifetime, ApplicationLifetime>();
webAppServices.AddSingleton<IWebHostEnvironment>(hostingEnv);
webAppServices.AddSingleton<IConfiguration>(configRoot);
webAppServices.AddLogging();
```

I will also add the  `webAppServices.AddLogging()` to the next release.

For `Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions,``Exception:
Could you please share your `dotnet --info` and `func -v` output?

I´m using the Zip Deployment via Visual Studio or the Deployment task of an AzureDevOps pipeline for deploying my apps. I could deploy the Razorpages-Template without setting `<RuntimeIdentifier>linux-x64</RuntimeIdentifier> <SelfContained>true</SelfContained>` in the Functions project file. 

https://nlserverlessaspnetcorefunctionapp20200123110536.azurewebsites.net/

Be sure that the Runtime of the AppService is set to V3
![image](https://user-images.githubusercontent.com/6589385/73028584-1d5cd280-3e36-11ea-83d3-142a338c250a.png)

**Comment by tntwist** [comment]
> Well, it seems that all is working now. I'm not entirely sure what was going on, but I recreated the Function and switched the runtime to `~3`. I had though that `AzureFunctionsVersion` in the csproj would have been enough to switch it on deploy and/or display an error.

I was so distracted writing my comment that i haven´t noticed your reply :) I´m glad its working for you now.
